---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: worthly
      sources:
        stages:
          - dev
  promotionTemplate:
    spec:
      steps:
        - uses: argocd-update
          config:
            apps:
              - name: worthly-prod
                namespace: argocd
                sources:
                  - repoURL: https://github.com/kbdevops/homelab-k8s
                    desiredRevision: main
                    kustomize:
                      images:
                        - image: registry.registry:5000/worthly
                          fromOrigin:
                            kind: Warehouse
                            name: worthly