---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: worthly
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`worthly.internal`)
      services:
        - name: worthly
          port: 5050