---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: worthly

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml

images:
  - name: ghcr.io/kbdevops/worthly
    newTag: latest  # Kargo will update this tag